### ISSUE TITLE
Login error with swiss pass 

### ISSUE THREAD

**Issue by TimonKuhn** [SchweizerischeBundesbahnen/api-principles#37]
We are a student group from FHNW, working on an API-consuming backend.
We would like to use your API, but we do not manage:

https://developer.sbb.ch/home
here we can log in an sign up for api's, but we never get past a "pending" state

https://developer-int.sbb.ch/home
here we would much rather like to work on, but we cannot loggin with the swiss ID, it always shows "Sie konnten nicht eingeloggt werden. Bitte überprüfen Sie Ihre Angaben." when you enter the E-mail, before you even get to the point of entering the password. Happens with different accounts and browsers.

Cheers - thankfull for every help

**Comment by thpeng** [comment]
Hi Timon

Glad that you would like to use the API management platform of the SBB. Not every API is accessible to the public. This might be because of legal or commercial limitations. You might get a hint if you can use an API for your purpose if the 'Plan' youre choosing on an API does not have the line 'Approval required'. E.g. https://developer.sbb.ch/apis/atlas/plans has a public plan for reading customer information and other which require an approval. 

If you don't find what you need you might look into the Open Data Platform of the SBB at https://data.sbb.ch/pages/home/

If you have still some questions drop me a mail at thierry.peng at sbb.ch.

**Comment by TimonKuhn** [comment]
Hey Thierry

Thanks for your help - I did not find any other way to contact you guys, so nice that this worked.

We are still confused about the which one we should use for our semester project


https://developer-int.sbb.ch/

https://developer.sbb.ch/

as described, we do not get access to the first one but we are meerly testing and not building an productive app for long scoped usage (after June the project will be finidshed.)

Just for clarification: these https://data.sbb.ch/pages/home/ are no API's, but "only" datasets which are published up to every five minutes? (The assignment states that we have to use an API...)

Beste Grüsse
Timon Kuhn

Timon Kuhn
Präsident Fachschaft students.habg
Mitglied Vorstand students.fhnw
Klassensprecher G6
Student BSc Geomatik
FHNW / HABG Muttenz
+41 079 842 35 99
***@***.***


________________________________
Von: Thierry Peng ***@***.***>
Gesendet: Dienstag, 2. April 2024 22:08
An: SchweizerischeBundesbahnen/api-principles ***@***.***>
Cc: Timon Kuhn (s) ***@***.***>; Author ***@***.***>
Betreff: Re: [SchweizerischeBundesbahnen/api-principles] Login error with swiss pass (Issue #37)


Hi Timon

Glad that you would like to use the API management platform of the SBB. Not every API is accessible to the public. This might be because of legal or commercial limitations. You might get a hint if you can use an API for your purpose if the 'Plan' youre choosing on an API does not have the line 'Approval required'. E.g. https://developer.sbb.ch/apis/atlas/plans has a public plan for reading customer information and other which require an approval.

If you don't find what you need you might look into the Open Data Platform of the SBB at https://data.sbb.ch/pages/home/

If you have still some questions drop me a mail at thierry.peng at sbb.ch.

**Comment by thpeng** [comment]
Hi Timon

I had to check the behavior you described and its intended (but also confusing from your point of view). The int stage is connected to another identity provider, so your (production) Swisspass does not work there. 

In my opinion you have two options. Either you're working with  APIs on developer.sbb.ch which do not require any approval or you're using the data from data.sbb.ch. It is true, that the data can be downloaded as a dataset. But for most data there is also an API provided see for example https://data.sbb.ch/explore/dataset/dienststellen-gemass-opentransportdataswiss/information/ and the api is located here: https://data.sbb.ch/api/explore/v2.1/catalog/datasets/dienststellen-gemass-opentransportdataswiss/records?limit=20 

I'll close this issue now because it is unrelated to our api-principles. If you need further assistance please write an email 

Best Regards

Thierry
